name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments
      - run: npm install
      - run: ls node_modules
      - run: pm run test:ci
